-- Seed data for BetterMinds Financial Rebuilding Platform

-- Insert vetted financial products
INSERT INTO public.product_directory (name, provider_name, type, supported_states, requires_permanent_address, requires_credit_check, monthly_fee, affiliate_link, red_flags, is_vetted) VALUES
('Bank On Certified Accounts', 'Various Banks', 'checking', ARRAY['All States'], true, false, 0.00, NULL, NULL, true),
('Capital One Secured Credit Card', 'Capital One', 'secured_card', ARRAY['All States'], true, false, 0.00, NULL, NULL, true),
('Discover it® Secured Credit Card', 'Discover', 'secured_card', ARRAY['All States'], true, false, 0.00, NULL, NULL, true),
('Self Credit Builder Account', 'Self Financial', 'credit_builder_loan', ARRAY['All States'], true, false, NULL, NULL, ARRAY['Administrative fees vary'], true),
('Local CDFI Credit Builder Loans', 'Community Development Financial Institutions', 'credit_builder_loan', ARRAY['Varies'], true, true, NULL, NULL, NULL, true),
('National Foundation for Credit Counseling', 'NFCC', 'counseling_org', ARRAY['All States'], false, false, NULL, NULL, NULL, true),
('Chime Second Chance Banking', 'Chime', 'checking', ARRAY['All States'], true, false, 0.00, NULL, NULL, true),
('Green Dot Prepaid Card', 'Green Dot', 'checking', ARRAY['All States'], true, false, 7.95, NULL, ARRAY['High monthly fees compared to bank accounts'], false),
('NetSpend Prepaid Card', 'NetSpend', 'checking', ARRAY['All States'], true, false, 7.95, NULL, ARRAY['High fees for basic services'], false),
('ACE Cash Express', 'ACE Cash Express', 'credit_builder_loan', ARRAY['Select States'], true, false, NULL, NULL, ARRAY['Predatory lender with extremely high interest rates (300%+ APR)'], false);

-- Note: Knowledge embeddings require actual vector embeddings
-- This is a placeholder structure - you'll need to generate actual embeddings
-- for the content below using an embedding service like OpenAI's text-embedding-3-small

-- For now, we'll insert the knowledge content without embeddings
-- The embeddings can be added later via the application

INSERT INTO public.knowledge_embeddings (title, category, content, embedding) VALUES
('What is a secured credit card?', 'credit_building', 'A secured credit card is a type of credit card that requires a cash deposit as collateral. This deposit usually becomes your credit limit. For example, if you deposit $200, you can spend up to $200. Secured cards are designed for people looking to build or rebuild credit. Unlike prepaid cards, secured cards report to credit bureaus, so responsible use can help improve your credit score over time.', NULL),
('Restitution vs. Credit Debt', 'restitution', 'Restitution is court-ordered money you must pay as part of a criminal sentence. It is not the same as credit card debt or loans. Restitution does not typically appear on your credit report or affect your credit score directly. However, if you do not pay, it can lead to other legal consequences. Credit debt comes from credit cards, loans, or other financial products. Both are important to address, but they work differently and require different approaches.', NULL),
('How to get your free credit report', 'credit_reports', 'You can get your free credit report once a week from each of the three major credit bureaus (Equifax, Experian, and TransUnion) by visiting AnnualCreditReport.com. This is the official website authorized by federal law - be careful of other sites that charge fees. You will need to provide personal information to verify your identity. Review your report carefully for any errors or accounts you do not recognize.', NULL),
('How to dispute credit report errors', 'credit_reports', 'If you find errors on your credit report, you can dispute them for free. Contact the credit bureau that has the error in writing. Include your name, address, what you are disputing, and why. The bureau must investigate within 30 days. If they find the information is wrong, they must remove it. You can also file a dispute directly with the company that provided the incorrect information. Keep copies of everything you send.', NULL),
('Predatory products to avoid', 'financial_education', 'Be careful of: Payday loans - these have extremely high interest rates (often 400%+). Rent-to-own stores - you end up paying 2-3x the item is actual cost. High-fee prepaid cards - some charge monthly fees, ATM fees, and per-transaction fees. "Credit repair" companies that promise quick fixes - legitimate credit repair takes time and can often be done yourself for free. Title loans - these use your car as collateral and have very high rates.', NULL),
('ID recovery basics', 'id_recovery', 'Getting your ID back after incarceration varies by state. Generally, you will need: Proof of identity (birth certificate or passport), Proof of residency (utility bill, lease, or letter from a shelter), Social Security card, and sometimes a court order or release papers. Many states have reduced fees or expedited processes for formerly incarcerated individuals. Contact your local DMV or a reentry organization for state-specific help.', NULL),
('Second-chance bank accounts', 'banking', 'Second-chance bank accounts are designed for people who may have had trouble opening accounts before, often due to past banking issues or limited credit history. These accounts have the same basic features as regular checking accounts but may have lower limits or small monthly fees. Look for banks that: Do not use ChexSystems or have alternatives, offer a path to upgrade to a regular account, have low or no monthly fees, and provide financial education resources.', NULL),
('Building credit from scratch', 'credit_building', 'Building credit takes time but is definitely possible. Key steps include: 1) Pay all bills on time - this is the biggest factor in your score. 2) Keep credit card balances low (under 30% of your limit). 3) Do not open too many accounts at once. 4) Keep old accounts open to show a longer credit history. 5) Use a secured card or credit builder loan to establish positive payment history. Consistency is more important than speed.', NULL),
('Understanding credit scores', 'credit_education', 'A credit score is a three-digit number that shows how likely you are to repay debts. Scores range from 300 to 850. Higher scores mean better credit. Lenders use credit scores to decide if they will lend you money and what interest rate to charge. Your score is based on: Payment history (35%), amounts owed (30%), length of credit history (15%), new credit (10%), and types of credit used (10%). Building good credit takes time, but it is worth it for better financial opportunities.', NULL),
('Budgeting basics', 'financial_education', 'A budget is a plan for how you will spend and save your money. Start by listing all your income (wages, benefits, etc.). Then list all your expenses (rent, food, transportation, etc.). Subtract expenses from income to see if you have money left over. If expenses are more than income, look for ways to cut costs or increase income. Budgeting helps you make sure you can pay your bills and save for the future. There are many free apps and tools to help with budgeting.', NULL);
